### ISSUE TITLE
Add default value (optional fields)

### ISSUE THREAD

**Issue by joshmedeski** [justinsgithub/wezterm-types#2]
Thank for this project! I'd like to add support for optional fields so warnings aren't shown if fields aren't included.

![SCR-20240617-inra](https://github.com/justinsgithub/wezterm-types/assets/2036594/5da27b08-44c5-45a8-b628-886f18e0ce8a)

**Comment by justinsgithub** [comment]
My life took such a drastic turn away from software development, this makes my heart ache a little bit. I will keep this in mind if i ever get any free free time but can't make any promises at this point. Here is a thread about Lua types for Wezterm, hopefully an automated solution can be found [https://github.com/wez/wezterm/issues/3132](https://github.com/wez/wezterm/issues/3132).

**Comment by joshmedeski** [comment]
Wishing the best for you @justinsgithub 🙏

Looks like some others are making progress on this in the issue you linked to, thanks for the response!

**Comment by snoblenet** [comment]
this did the trick for me:

```
---@diagnostic disable: missing-fields
```
